name: 'Graphql Downloader'
description: 'Download some GraphQL'
inputs:
  OWNER:
    description: "Input to use"
    default: "world"
  REPO:
    description: "Input to use"
    default: "world" 
  GH_TOKEN:
    description: "Input to use"
    default: "world"    
outputs:
  success: # id of output
    description: 'Run info message'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.OWNER }}
    - ${{ inputs.REPO }}
    - ${{ inputs.GH_TOKEN }}
    
