name: 'Graphql Downloader'
description: 'Download some GraphQL'
inputs:
  owner:
    description: "Code owner"
    default: "github"
  repo:
    description: "Repo name"
    default: "view_component" 
  gh_token:
    description: "Input to use"
    default: "1234"
  outfile:
    description: "Filename"
    default: "downloaded.json" 
outputs:
  success: # id of output
    description: 'Run info message'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.reop }}
    - ${{ inputs.gh_token }}
    - ${{ inputs.outfile }}

    
