name: "Python Container Action Template"
description: "Get started with Python Container actions"
author: "Jacob Tomlinson"
inputs:
  owner:
    description: "Input to use"
    default: "world"
  repo:
    description: "Input to use"
    default: "world"
  gh_token:
    description: "Input to use"
    default: "world"
  outfile:
    description: "Output file to use"
    default: "alerts.json"  
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
