name: "Python Container Action Template"
description: "Get started with Python Container actions"
author: "Jacob Tomlinson"
inputs:
  owner:
    description: "Input to use"
    default: "world"
  repo:
    description: "Input to use"
    default: "world"
  gh_token:
    description: "Input to use"
    default: "world"
  query:
    description: "GraphQL query to use"
    default: >
      query dependaBotAlerts($owner: String!, $repo: String!) {
            repository(owner: $owner, name: $repo) {
            vulnerabilityAlerts(first: 100) {
                nodes {
                createdAt
                dismissedAt
                securityVulnerability {
                    package {
                    name
                    ecosystem
                    }
                    advisory {
                    severity
                    summary
                    description
                    notificationsPermalink
                    ghsaId
                    }
                    vulnerableVersionRange
                }
                }
            }
            }
        }
  outfile:
    description: "Output file to use"
    default: "alerts.json"  
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
