name: DownloadQL ext test

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  downloadAlerts:
    name: Download GQL to JSON 📥
    runs-on: ubuntu-latest
    steps:

      - name: Get secret from base64
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo import certificate from secrets and regenerate the file
          echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.keystore
      - name: Download the QL
        id: download
        uses: zackn9ne/graphql_downloader@main
        with:
          owner: ${{ github.event.repository.owner.name }}
          #repo: ${{ github.event.repository.name }}
          repo: ${{ secrets.SECRET_REPO }}
          gh_token: ${{ secrets.INSOMNIA_KEY }}
          outfile: "alerts.json"

      - name: catfile
        run: |
          cat $GITHUB_WORKSPACE/app/${{ steps.download.outfile }}
