name: DownloadQL ext test

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  downloadAlerts:
    name: Download GQL to JSON 📥
    runs-on: ubuntu-latest
    steps:
      - name: Download the QL
        id: download
        uses: zackn9ne/graphql_downloader@main
        with:
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
          #repo: ${{ secrets.SECRET_REPO }}
          gh_token: ${{ secrets.FULLB64 }}
          outfile: "alerts.json"

      - name: catfile
        run: |
          ls
          pwd
          echo ${{ steps.download.myOutput }}
          cat alerts.json
